name: Fantasy Football Data Pipeline

on:
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
# /home/runner/work/fantasyfootball/fantasyfootball      
      PYTHONPATH: ${{ github.workspace }} 
# /home/runner/work/fantasyfootball/fantasyfootball/data      
      DATA_PIPELINE_ROOT: ${{ github.workspace }}/data

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install
    
    - name: Display PythonPath
      run: echo $PYTHONPATH

    - name: Print working directory
      run: pwd

    - name: Collect Average Draft Position
      run: poetry run python -m pipeline.collect.collect_adp

    - name: Write Average Draft Position
      uses: actions/upload-artifact@v4
      with:
        name: raw-adp-files
        path: ./data/raw/adp/**/*.csv

    # - name: Collect Player Stats
    #   run: poetry run python ./pipeline/collect/collect_stats.py

    # - name: Write Player Stats
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: raw-stats-files
    #     path: /home/runner/work/data/raw/stats/*.csv

    - name: Process Average Draft Position
      run: poetry run python -m fantasyfootball.pipeline.process.process_adp

    - name: Write Processed ADP files
      uses: actions/upload-artifact@v4
      with:
        name: processed-adp-files
        path: ./data/processed/adp/**/*.csv

    # - name: Process Player Stats
    #   run: poetry run python ./pipeline/process/process_stats.py

    # - name: Write Processed stats files
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: processed-stats-files
    #     path: /home/runner/work/data/processed/stats/**/*.csv